version: '3.4'
services:
  app:
    # image: node:12
    build:
      context: .
      target: dev
    volumes:
      - ./index.js:/app/index.js
    working_dir: /app
    command: npm start
    environment:
      - NODE_ENV=development
    ports:
      - 3000:3000
